site_name: Wiki Mosqueteroweb · Salud
site_description: Recopilatorio personal de salud, utilidades y curiosidades
site_dir: _site
theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - navigation.top
    - search.suggest
    - search.highlight
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - markdown.extensions.md_in_html
  - attr_list
